### ISSUE TITLE
Does the client respond to POST requests with status 200 by default?

### ISSUE THREAD

**Issue by imthatcarlos** [hyperoslo/facebook-messenger#104]
I see that that there isn't a default hook (like Bot.on :default or something like that), so I'm wondering if the client isn't acknowledging some requests.

**Comment by enderahmetyurt** [comment]
why do we need default request? If request is not registered, some error raises. https://github.com/hyperoslo/facebook-messenger/blob/master/lib/facebook/messenger/bot.rb#L42

**Comment by imthatcarlos** [comment]
Right, but what I meant was for some way for 200 to be sent back when, for example, FB sends random ping to make sure app is alive.

**Comment by jgorset** [comment]
We do, @imthatcarlos (see https://github.com/hyperoslo/facebook-messenger/pull/102). [`Rack::Response#finish`](https://github.com/hyperoslo/facebook-messenger/blob/master/lib/facebook/messenger/server.rb#L34) runs either way.
