### ISSUE TITLE
Support to `mark_seen` sender action option

### ISSUE THREAD

**Issue by FlaviaFortes** [hyperoslo/facebook-messenger#106]
I'm not sure this is the proper place to make this question, but if you could help me: The `facebook_messenger` gem has support for the `mark_seen` option?

I found it here: https://developers.facebook.com/docs/messenger-platform/send-api-reference/sender-actions

**Comment by ylecuyer** [comment]
Mean while you can use : 

```
Facebook::Messenger::Bot.deliver(
{recipient: 
    message.sender, 
    sender_action: 'mark_seen'},
access_token: "")

```
