### ISSUE TITLE
Problem confirmation webhook

### ISSUE THREAD

**Issue by akushneruk** [hyperoslo/facebook-messenger#112]
![screenshot from 2017-02-17 19-34-24](https://cloud.githubusercontent.com/assets/7112520/23078160/3497d1d4-f550-11e6-8e72-8c3e30465c75.png)

**Comment by akushneruk** [comment]
I always get the message while maintaining webhook

**Comment by enderahmetyurt** [comment]
Did you select your facebook page for the bot?

**Comment by akushneruk** [comment]
![screenshot from 2017-02-17 23-14-56](https://cloud.githubusercontent.com/assets/7112520/23084128/82cfced8-f569-11e6-8b51-886f4b288301.png)
Yes

**Comment by enderahmetyurt** [comment]
No I mean Webhook section below the Token Generation section.

**Comment by akushneruk** [comment]
I get a request from facebook, but can not track whether
![screenshot from 2017-02-18 14-08-43](https://cloud.githubusercontent.com/assets/7112520/23093257/c6455020-f5e6-11e6-9eac-66674a3db1f3.png)

**Comment by akushneruk** [comment]
I figured out the problem was variable API. thank you
