### ISSUE TITLE
How will the new persistent menus change?

### ISSUE THREAD

**Issue by echan00** [hyperoslo/facebook-messenger#118]
Looks like we'll need to update this gem for the new menu design as well?

https://developers.facebook.com/docs/messenger-platform/messenger-profile/persistent-menu

**Comment by fcatuhe** [comment]
Hello, not yet confident about my programming skills to modify the gem, but from my analysis we at need to change "base_uri" in facebook-messenger/lib/facebook/messenger/thread.rb, from 'https://graph.facebook.com/v2.6/me' to 'https://graph.facebook.com/v2.6/me/messenger_profile', according to 'https://developers.facebook.com/docs/messenger-platform/messenger-profile/persistent-menu'.

Then the structure of the hash you pass is also different, but this is not hard-coded in the gem.

**Comment by echan00** [comment]
Yes @fcatuhe, it looks like this is how we would go about this change.

I've never this done before, but I could try to submit a revision for it.

**Comment by echan00** [comment]
https://github.com/hyperoslo/facebook-messenger/pull/119
