### ISSUE TITLE
Read timeout sending big files

### ISSUE THREAD

**Issue by pjpires** [hyperoslo/facebook-messenger#120]
I don't know if any of you guys already tried to post a large video. As currently I'm using the attachments reuse feature (https://github.com/hyperoslo/facebook-messenger/pull/116) I need the POST to succeed and return the attachment id. 

Since we're using HTTParty to make the requests, the default `read_timeout` value is set to 60 seconds, and the POST will fail (the video will still get delivered to the chat, which is also bad since the developers may assume it failed and try to resend it).

Probably this value should be configurable, or at least have it with a value that allows for uploading a large video/file.

**Comment by jgorset** [comment]
Good catch. Let's just default this to a reasonably large value.
