### ISSUE TITLE
Referral event not working

### ISSUE THREAD

**Issue by alenteria** [hyperoslo/facebook-messenger#121]
I am trying this 
```ruby
Bot.on :referral do |referral|
  referral.sender    # => { 'id' => '1008372609250235' }
  referral.recipient # => { 'id' => '2015573629214912' }
  referral.sent_at   # => 2016-04-22 21:30:36 +0200
  referral.ref       # => 'MYPARAM'
end
```

and I got an error
> referral is not a valid event; available events are message,delivery,postback,optin,read,account_linking

**Comment by jgorset** [comment]
That's odd. Is your Facebook application [subscribed to `messaging_referral`](https://developers.facebook.com/docs/messenger-platform/webhook-reference/referral)?

**Comment by alenteria** [comment]
@jgorset yes the fb app was subscribed already.
I found the root cause
see screenshot
![image](https://cloud.githubusercontent.com/assets/2783217/23863931/06e05ff4-084c-11e7-87ee-30bcaa50e140.png)
`referral` event is not included there.

**Comment by alenteria** [comment]
I just fixed it. I was pulling a version that don't support referrral yet.
I just explicitly specified the repo in my Gemfile
`gem 'facebook-messenger', git: "git@github.com:hyperoslo/facebook-messenger.git"`
It's working now.
