### ISSUE TITLE
Development environment issues, ngrok?

### ISSUE THREAD

**Issue by echan00** [hyperoslo/facebook-messenger#125]
Anybody having issues in your development environment? 

I find that messages/postbacks are frequently ignored. It will start working again if I wait a while or interact with the bot with other messages/postbacks, but this is obviously a major pain during development.

Anybody else with similar problems? Could it be Ngrok?

**Comment by ajose01** [comment]
I believe this is more of a Facebook issue.

I develop for both kik and fb without the use of this gem, and it seems that when ever fb doesn't get a response, they put a sleep on sending you additional messages. 

Likely a good feature if there's explosions happening they don't keep bombarding your webhook.

Kik doesn't care... they keep firing in the hole! LOL

**Comment by echan00** [comment]
@ajose01 What do you mean when FB doesn't get a response?

**Comment by ajose01** [comment]
If you're in you're dev environment, and something goes wrong you might not respond with a 200. 

So when this happens I've noticed FB puts a slight hold before they start sending you packets again. 

If you look at ngrok, you won't see any traffic coming through.

**Comment by echan00** [comment]
Hmm, the problem I have happens even when something doesn't go wrong... meaning after a few minutes everything works when no code was changed.

**Comment by ajose01** [comment]
Only thing I can think of at the moment is maybe you're not responding with a 200 status code right away?

**Comment by echan00** [comment]
Okay, maybe thats the case. 

If you don't mind me asking, what are you using to return 200?

**Comment by echan00** [comment]
Nevermind, silly question.

**Comment by echan00** [comment]
Actually, it didn't fix my issue... so I guess returning 200 isn't the issue.

**Comment by ChocoMilkTea** [comment]
It happens to me too. How to make it so that facebook stop ignoring messages/postbacks?

**Comment by jgorset** [comment]
I've been developing with ngrok, too, but I haven't experienced this. Are you sure that you're responding to all of Facebook's requests to your bot? It'd be helpful to see logs.

**Comment by jgorset** [comment]
I'm closing this pending logs.
