### ISSUE TITLE
Post back event issue

### ISSUE THREAD

**Issue by bvhieu106** [hyperoslo/facebook-messenger#126]
i ready don't understand why nothing any postback event in log
have app need permission? or any config missing with me?
Pls help me
page config
![image](https://cloud.githubusercontent.com/assets/11210043/24032059/a79a7834-0b18-11e7-9061-01d3a4fe02ac.png)

![image](https://cloud.githubusercontent.com/assets/11210043/24032073/bb128348-0b18-11e7-9c87-213acc3c7be5.png)

but log don't have event postback

**Comment by SylarRuby** [comment]
Nothing is wrong with the gem. Maybe ur webhook url is the issue. Create another fb page and try a fresh clean app

**Comment by bvhieu106** [comment]
Thanks you so much
We have any issue to discuss about submit request permission for app?

**Comment by jgorset** [comment]
There's no issue for that, but feel free to make one!

**Comment by bvhieu106** [comment]
thanks so much
