### ISSUE TITLE
Undefined method 'typing_on'

### ISSUE THREAD

**Issue by Amval** [hyperoslo/facebook-messenger#128]
I get this error when using `typing_on`:

```
NoMethodError (undefined method `typing_on' for #<Facebook::Messenger::Incoming::Message:0x0055d7c990a500>):
  
app/bot/listen.rb:12:in `block in <top (required)>'
Error occurred while parsing request parameters.
Contents:
```

I am just following the `README.md` example. Looks like [I am not the only one](https://github.com/hyperoslo/facebook-messenger/issues/123) having this problem.

**Comment by jgorset** [comment]
Hi @Amval! This change hadn't made it to RubyGems yet, but I just released a new version.
