### ISSUE TITLE
Multiple Pages

### ISSUE THREAD

**Issue by edos4** [hyperoslo/facebook-messenger#129]
Hi! Reading the Readme, specifically the "If your bot lives on multiple Facebook Pages". Upon checking [Providers::Base](https://github.com/hyperoslo/facebook-messenger/blob/master/lib/facebook/messenger/configuration/providers/base.rb) it is not yet implemented due to the `raise NotImplementedError`. 

Am I right? Else, how do you store multiple verify_token, app_secret, and access_token?

**Comment by jgorset** [comment]
Hi @edos4!

`Providers::Base` is just an abstract base class that you can extend to build your own configuration provider, like we've demonstrated in the README. The reason we're not shipping a configuration provider with the gem is that where you get the configuration from is highly dependant on your application and we don't want to impose any dependencies on you.

**Comment by jover619** [comment]
Hi @jgorset , is it possible to do multiple pages huh? If yes, can you give me a guide on how to do it?

**Comment by jgorset** [comment]
The bit about [configuration providers in the README](https://github.com/hyperoslo/facebook-messenger#make-a-configuration-provider) is basically that guide; all you have to do is make one for yourself to get the right verify token, app secret and access token for the provided `page_id`.
