### ISSUE TITLE
Error while run console

### ISSUE THREAD

**Issue by IgorLeonenko** [hyperoslo/facebook-messenger#138]
When I want to run rails console via `rails c` or `bundle exec rails c` whatever it's return error: `'.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/facebook-messenger-0.11.1/lib/facebook/messenger/subscriptions.rb:36:in 'raise_errors': An active access token must be used to query information about the current user. (Facebook::Messenger::Subscriptions::Error)`

**Comment by jgorset** [comment]
It sounds like your access token is invalid. Did you set it according to the [README](https://github.com/hyperoslo/facebook-messenger#make-a-configuration-provider), and are you sure that it's valid?

**Comment by IgorLeonenko** [comment]
Yes! It's completely valid and installed correctly because, when I run `rails s` and start "speak" to bot - all works as expected.

**Comment by jgorset** [comment]
Alright, can I see your full stack trace and code please?

**Comment by jgorset** [comment]
I'm closing this pending stack trace and code.
