### ISSUE TITLE
uninitialized constant Facebook::Messenger::Profile (NameError)

### ISSUE THREAD

**Issue by Cyangen** [hyperoslo/facebook-messenger#139]
HI, I'm getting error saying: 

> uninitialized constant Facebook::Messenger::Profile (NameError).

this is my code:
`Facebook::Messenger::Profile.set({
   greeting: [
       {
           locale: 'default',
           text: 'Welcome to MyApp!'
       }
   ]
}, access_token: ENV['ACCESS_TOKEN'])`

I'm using gem version 0.11.1
what's wrong?
Thanks.

**Comment by progapandist** [comment]
Hi! Just require your gem with a link to github in your Gemfile, like that: 
```
gem 'facebook-messenger', github: 'hyperoslo/facebook-messenger'
```
Then `bundle install`. That way you use the last dev version of the gem. The feature did not make it to the official release yet, but the readme was already updated.

**Comment by Cyangen** [comment]
Thank you @progapandist, now it work!
