### ISSUE TITLE
How to use Facebook Test App for development

### ISSUE THREAD

**Issue by spencerldixon** [hyperoslo/facebook-messenger#140]
I'd like to register two clients with facebook and have one for production and one for continued development. 

The production app has been working fine with ngrok but changing the tokens out for the development one comes up with the error: `An active access token must be used to query information about the current user.`

Has anyone come across this?

**Comment by spencerldixon** [comment]
Problem solved. The solution was that the gem relies on your env variable being called `ACCESS_TOKEN`, `APP_SECRET`, `VERIFY_TOKEN` and nothing else.

Once that's in, you can create two facebook pages, and unpublish one, and just follow the regular set up to register an app against each one and get two sets of tokens, one for a development page and one for a production page.

**Comment by fcatuhe** [comment]
Hey there, although this is closed, here is a hint on how I use the configuration provider to deal with 2 bots:
`class BotProvider < Facebook::Messenger::Configuration::Providers::Base
  def valid_verify_token?(verify_token)
    (verify_token == ENV['BOT_VERIFY_TOKEN'])
  end

  def app_secret_for(page_id)
    case page_id['id']
    when ENV['YVON_PAGE_ID']
      ENV['YVON_APP_SECRET']
    when ENV['ALINE_PAGE_ID']
      ENV['ALINE_APP_SECRET']
    end
  end

  def access_token_for(page_id)
    case page_id['id']
    when ENV['YVON_PAGE_ID']
      ENV['YVON_ACCESS_TOKEN']
    when ENV['ALINE_PAGE_ID']
      ENV['ALINE_ACCESS_TOKEN']
    end
  end
end
`
I put this file in the app/bot/ folder.

Hope it helps.

**Comment by jgorset** [comment]
Nice, @fcatuhe!
