### ISSUE TITLE
uninitialized constant Facebook::Messenger::Subscriptions

### ISSUE THREAD

**Issue by nekapoor** [hyperoslo/facebook-messenger#143]
Hello!

I'm using an existing Rails 4 application to get setup with facebook-messenger and I can't seem to figure out why things aren't working. 

I've used the eager loading instructions and copied them exactly. 

But when I run my rails s, I get the error: 

`uninitialized constant Facebook::Messenger::Subscriptions`

In my example.rb file, I've put the following: 

    require 'facebook/messenger'

    include Facebook::Messenger

    Facebook::Messenger::Subscriptions.subscribe(access_token: ENV["access_token"])

    Bot.on :message do |message|
      message.reply(text: 'Hello, human!')
    end

And if I were to remove the Facebook::Messenger::Subscriptions line, then I'd get an error that says: 

`uninitialized constant Bot`

Any thoughts?

**Comment by alfredosotoz** [comment]
I'm having a similar issue:
An active access token must be used to query information about the current user. (Facebook::Messenger::Subscriptions::Error)

Have double check my access token and other env variables, it seems all are good but continues sending error

**Comment by echan00** [comment]
Did you add to routes.rb? & create an initializer as instructed?

**Comment by nekapoor** [comment]
@echan00 yeah I've added 

`mount Facebook::Messenger::Server, at: 'bot'` 

to routes.rb

I've also created a bot.rb in my config/initializers folder.

**Comment by jgorset** [comment]
Hi @nekapoor!

You're not supposed to subscribe your bot to the page more than once, so remove that bit and just run it once in your console.

Try to remove `include Facebook::Messenger` and instead spell out `Facebook::Messenger::Bot` and see if that helps.
