### ISSUE TITLE
Unable to access database

### ISSUE THREAD

**Issue by aharonhillel** [hyperoslo/facebook-messenger#146]
Hi everyone,
I setup the bot as described and everything works until I try an active record query to my database. This fails. Is this because there is no controller? Currently I made a new folder app/bots and put the file in there. Am I doing something wrong? I want my chatbot to be able to access a table and retrieve information. 
Thanks, 
Aaron

**Comment by jgorset** [comment]
Hi @aharonhillel. This sounds like an issue with your Rails application rather than this gem, but to be able to help we need the exact error and stack trace.

**Comment by jgorset** [comment]
Feel free to reopen this if you're still having this issue.
