### ISSUE TITLE
To_prepare Missing

### ISSUE THREAD

**Issue by aharonhillel** [hyperoslo/facebook-messenger#147]
Hi, 
I am running the newest version of rails 5.1, and I am getting an error because "to_prepare" was recently deprecated. Any suggestions on how to fix the gem?

The code that calls it is 
`ActionDispatch::Callbacks.to_prepare do
    bots_reloader.execute_if_updated
  end`

Thanks!

**Comment by abury** [comment]
@aharonhillel 
In your bot initializer Just replace:
```ruby
ActionDispatch::Callbacks.to_prepare
```

with:
```ruby
ActiveSupport::Reloader.to_prepare
```

Full init code should be:
```ruby
unless Rails.env.production?
  bot_files = Dir[Rails.root.join('app', 'bot', '**', '*.rb')]
  bot_reloader = ActiveSupport::FileUpdateChecker.new(bot_files) do
    bot_files.each{ |file| require_dependency file }
  end

  ActiveSupport::Reloader.to_prepare do
    bot_reloader.execute_if_updated
  end

  bot_files.each { |file| require_dependency file }
end
```

Tested and working fine on my end.

**Comment by jgorset** [comment]
Thanks @abury! I've been wanting to fix that, but since I don't really use Rails anymore I just didn't get around to looking at what they replaced it with. I updated the README accordingly in #152.
