### ISSUE TITLE
Please push latest changes to rubygems!

### ISSUE THREAD

**Issue by BonMatts** [hyperoslo/facebook-messenger#148]
Hey! the current version on rubygems is 0.11.0, and I need to changes in #135, and I'd rather not refer to a specific github commit in my gemfile.
Thanks!

**Comment by filipebarcos** [comment]
Not only that. Simple things like `message.mark_seen` is not available in `0.11.1`.

Latest is actually `0.11.1` in Rubygems, btw.

**Comment by jgorset** [comment]
I just pushed 0.12 and 0.13 to RubyGems! 👍
