### ISSUE TITLE
Postbacks not Working

### ISSUE THREAD

**Issue by AlecRubin** [hyperoslo/facebook-messenger#15]
Hi, I am trying to set up the post backs in my app and have been unsuccessful. Also, nothing is showing in the logs, any ideas?

**Comment by jgorset** [comment]
The logs should definitely say something – if you've registered a hook on `:postback` it should run that code, and otherwise it should say that it's ignoring the event. Did you remember to [subscribe to the page](https://github.com/hyperoslo/facebook-messenger#subscribe-your-application-to-a-page)? Also, please help us to help you by sharing your code.

**Comment by AlecRubin** [comment]
Totally unrelated question, but is there a way to retrieve the sender's first name on either the message or postback method?

**Comment by jgorset** [comment]
Did you figure the first question out...?

**Comment by jgorset** [comment]
And yes, you can [use the Graph API to query user data](https://developers.facebook.com/docs/messenger-platform/send-api-reference#user_profile_request).

**Comment by AlecRubin** [comment]
Ok thanks, yeah everything is working now!

**Comment by dthyresson** [comment]
I know this issue is closed, but as an FYI to future readers, be sure when subscribing to the page to enable the `messaging_postbacks` event.

```
To receive messages and other events sent by Messenger users, the app should enable webhooks integration.
Selected events: message_deliveries, messages, messaging_optins, messaging_postbacks
```

When I initially setup my bot and webhooks, I only enabled the `messages` event (as shown in the README image).

**Comment by jgorset** [comment]
Good catch, @dthyresson! I just got that image from Facebook's documentation, but it'd be good to update it with something that has all the right settings.

**Comment by vedant1811** [comment]
Hello. I am still facing the same issue :(
After sending this, I get the 2 quick reply options:

      optin.reply(
          text: "Welcome #{user.name}! Should I notify you of job updates via messages?",
          quick_replies: [
              {
                  content_type: 'text',
                  title: 'Yes, definitely',
                  payload: 'notifications-yes'
              },
              {
                  content_type: 'text',
                  title: 'No',
                  payload: 'notifications-no'
              }
          ]

but the, after selecting the 'yes. definitely' option, nothing happens in the postback callback:
    
    Bot.on :postback do |postback|
      postback_debug = {
          sender: postback.sender,
          payload: postback.payload,
      }
      Rails.logger.debug "New postback: #{postback_debug.to_s}"
      case postback.payload
        when 'notifications-yes'
          postback.reply(text: 'Great')
        when 'notifications-no'
          postback.reply(text: 'Okay :(')
        else
          raise "Cannot handle postback payload: #{postback.payload}"
      end
    end

However, I do get a message callback with `:text=>"Yes, definitely"`, as seen in my logs.

**Comment by jgorset** [comment]
A quick reply is not a postback, @vedant1811. Here's the [documentation on postbacks](https://developers.facebook.com/docs/messenger-platform/send-api-reference/postback-button).

**Comment by M-Abozaid** [comment]
I'm facing the same issue, it only occurs when I do broadcast

**Comment by MandalShankar** [comment]
I'm facing the same issue, Postbacks not Working for a particular facebook page but it is working for all other page. If am i doing any wrong with page setting pls help me
