### ISSUE TITLE
Welcome messages

### ISSUE THREAD

**Issue by jgorset** [hyperoslo/facebook-messenger#16]
We should facilitate for setting [welcome messages](https://developers.facebook.com/docs/messenger-platform/send-api-reference#welcome_message). Maybe something like `Facebook::Messenger::Welcome.set [...]`?

**Comment by sindrenm** [comment]
That's an extremely object-oriented suggestion you've got there. :grinning:

**Comment by jgorset** [comment]
How so, @sindrenm? 😛

**Comment by mengqing** [comment]
Should this be some sort of rake task as you would most likely to do this once? Same goes for deleting the welcome message

**Comment by jgorset** [comment]
I think it's a good idea to make it available from a rake task, @mengqing. The logic itself should probably be outside of rake, though, so as to be usable with a program and more easily testable. We did this for [`Facebook::Messenger::Subscriptions.subscribe`](https://github.com/hyperoslo/facebook-messenger/blob/master/lib/facebook/messenger/subscriptions.rb#L15).
