### ISSUE TITLE
Return sender first name, and gender

### ISSUE THREAD

**Issue by AlecRubin** [hyperoslo/facebook-messenger#26]
How can I return the senders first name, last name, and gender from the facebook graph api when a message is received?

**Comment by gauravtiwari** [comment]
@AlecRubin Can you not query the profile info from FB using the Sender ID? https://developers.facebook.com/docs/graph-api/reference/v2.6/user

For ex: 
Send a get request for this url: `https://graph.facebook.com/v2.6/${id}`

See more her: https://developers.facebook.com/tools/explorer/

**Comment by gauravtiwari** [comment]
With httparty, here is a rough code: 


```ruby
require 'httparty' # (if not already required)
include HTTParty

def get_sender_profile(sender)
  request = HTTParty.get(
    'https://graph.facebook.com/v2.6/#{sender}',  
    query: {
      access_token: ENV['ACCESS_TOKEN'],
      fields: 'first_name,last_name,profile_pic'
    }
  )
 
  request.parsed_response # or just request.body
end

# Once you have a message: 
Bot.on :message do |message|
  sender = get_sender_profile(message.sender)
  puts sender.inspect
end
```

I haven't tested this so, please refer to the API docs.

**Comment by gauravtiwari** [comment]
Oops guess you asked something different @AlecRubin, but not very clear. You mean return via Payload?

**Comment by jgorset** [comment]
Nope, I think you nailed it, @gauravtiwari! I'm closing this pending a response from @AlecRubin.

**Comment by gauravtiwari** [comment]
@jgorset cool 🎉 

Btw, @AlecRubin you can refer to this class: https://github.com/hyperoslo/facebook-messenger-demo/blob/master/app/bots/product_bot.rb, it has a lot of implementations for Bot API (even sending serialised data via Payload).

**Comment by zdne** [comment]
@gauravtiwari any chance adding this to the library? The code is trivial but re-writting the HTTParty error handling isn't fun ..

**Comment by gauravtiwari** [comment]
Hey @zdne, Yeah we could, but this library is not intended for fetching Facebook Graph data.  Adding it here would make the library heavy and violate SRP. Perhaps, you could use -  `Koala` to interact with Graph API: https://github.com/arsduo/koala/wiki/Graph-API 

Would this work?

**Comment by jgorset** [comment]
I agree with both of you; you'll want it very often, but it's not the right thing for this library to do. Let's add a bit about Graph API clients like Koala to the README.

**Comment by gauravtiwari** [comment]
@zdne Totally agree and it's very small thing, but just for SRP sake. Awesome! We will definitely add this to Readme, and you can totally do this too - just make a PR and we will merge it right in 👍
