### ISSUE TITLE
Undefined method "bytesize"

### ISSUE THREAD

**Issue by samstarling** [hyperoslo/facebook-messenger#37]
Have you ever seen anything like this, when using this in a Rails project?

```
NoMethodError (undefined method `bytesize' for nil:NilClass):
  rack (1.6.4) lib/rack/utils.rb:369:in `bytesize'
  rack (1.6.4) lib/rack/utils.rb:439:in `secure_compare'
  facebook-messenger (0.5.0) lib/facebook/messenger/server.rb:57:in `integrity?'
  facebook-messenger (0.5.0) lib/facebook/messenger/server.rb:41:in `receive'
  facebook-messenger (0.5.0) lib/facebook/messenger/server.rb:19:in `call'
  facebook-messenger (0.5.0) lib/facebook/messenger/server.rb:11:in `call'
```

**Comment by samstarling** [comment]
I just tried the same thing using a very basic example with `rackup` / `config.ru`, and get the same thing.

**Comment by nashby** [comment]
@samstarling hey, looks like one of the parameters in `Rack::Utils.secure_compare` call is `nil`. I'm assuming it's `app_sercret` that is nil. Can you check `Facebook::Messenger.config.app_secret` in your app?

**Comment by samstarling** [comment]
Yeah, I'm setting that:

```
Facebook::Messenger.configure do |config|
  config.access_token = '...'
  config.app_secret = '...'
  config.verify_token = '...'
end
```

**Comment by nashby** [comment]
@samstarling I see. I just created a sample app and can see that Facebook doesn't send `X-Hub-Signature` header to the webhook. @frodsan any idea?

**Comment by frodsan** [comment]
@nashby I tried my bot and I get the header (`"HTTP_X_HUB_SIGNATURE\"=>\"sha1=4f96c3...`).
I will try to set up a new bot.

It would be nice to implement error handling in any case (https://github.com/frodsan/fbot/blob/master/server.go#L63).

**Comment by frodsan** [comment]
@nashby @samstarling are you testing from Heroku?

**Comment by frodsan** [comment]
[23:55] I set up a new bot
[23:56] Send first messages. Received responses without header.
[00:04] Send a couple of messages. Received responses with header.

This is crazy! :-p

**Comment by frodsan** [comment]
I found this: http://unframework.com/facebook-bot-setup/

> Another weird confusing behaviour: FB infrastructure does not send the X-Hub-Signature header with the first few webhook requests. So the proper code setup cannot safely validate FB as the originator! Luckily, it seems to just start sending it after 10-15 minutes, maybe a strange timeout?

**Comment by nashby** [comment]
@frodsan that's true. I'm also started getting this header now. Oh well.

**Comment by jgorset** [comment]
Oh, Facebook! So I guess we should expect that the header isn't set and proceed gracefully if it isn't?

**Comment by frodsan** [comment]
That would defy the purpose of the header. Someone could send a request without it and the server code will proceed gracefully.

I think it's better to document this behaviour in the README and start handling errors properly.

```ruby
if x_hub_signature.empty?
  log("...")
end
```

Maybe?

**Comment by jgorset** [comment]
Haha, right, of course it would @frodsan. Tricky!

**Comment by samstarling** [comment]
Thanks for all your input! It sounds a bit messy if Facebook isn't reliably returning this header. Do you think this is a problem that they're having, or something intentional? I guess it's tricky to know...

**Comment by nashby** [comment]
I'm gonna write to Facebook about this issue. I'll keep you guys posted in this issue when they respond.

**Comment by frodsan** [comment]
https://developers.facebook.com/bugs/1018643274889129/
https://developers.facebook.com/bugs/993518330744418/

**Comment by jgorset** [comment]
I think we have to weigh the benefit of knowing that Facebook is the origin of the message versus ease of use of the library, then.

I think message spoofing would be pretty hard to abuse because there's not really much data you'd trust anyway. Really about the only data that you're getting from Facebook that isn't generated by the user is the message sender, so the worst thing that could happen is that a malicious user pretends to be someone else. The likelihood of that is hard, I think, as users are identified uniquely within each Facebook Page (I'm `12469139561` on Page A and `31623471457` on Page B).

Perhaps we should implement an error that better describes it, then, and mention it in the README when we talk about configuring the gem with `app_secret` so people know what to expect?

**Comment by nashby** [comment]
Yeah, I commented on the last one.

**Comment by frodsan** [comment]
> Perhaps we should implement an error that better describes it, then, and mention it in the README when we talk about configuring the gem with app_secret so people know what to expect if they need it?

👍 

Something like this? https://github.com/frodsan/facebook-messenger/commit/75b4c38eeb7bc4231b19413d763da22482b567d1

**Comment by frodsan** [comment]
Also,

> If any update sent to your server fails, Facebook will retry again immediately, and then a few more times with decreasing frequency over the next 24 hours. Updates that your server fails to accept after 24 hours will be dropped. Your server should handle deduplication of updates that may result from multiple attempts.

This means that it's very likely that you will get the messages even if the first requests fail. In this case, it's better to return 400 if that happens, instead of 200.

**Comment by jgorset** [comment]
Yeah, something like that! Maybe even link to the bug on Facebook's tracker, too, so one can tell why.

**Comment by jgorset** [comment]
Do you still have that commit, @frodsan? If so, wanna make it a pull request?

**Comment by frodsan** [comment]
@jgorset https://github.com/hyperoslo/facebook-messenger/pull/40

**Comment by jgorset** [comment]
:cake:

**Comment by jgorset** [comment]
I'm closing this, then!
