### ISSUE TITLE
more detailed readme

### ISSUE THREAD

**Issue by db0sch** [hyperoslo/facebook-messenger#38]
Hi all,
thank you for your hard work on this messenger bot gem.
I'm just starting using it. Can't wait to spend time coding the bot.
But, I must say that it was a bit hard, at the beginning to configure the bot.
I didn't really know where to put my code (like the Access Token bot challenge... etc).
I think, it would be nice to just give a classic pattern configuration, for easy set up.
Something like : 

Here is an easy configuration pattern on your rails app:
Only 3 files to create/edit:
* `app/bot/bot.rb` => that's where the token check challenge and all the bot code goes.
* `config/initializers/bot.rb` => where the loading code in dev/test environments goes.
* `config/routes.rb` => that's where you add the route/mount code for 'bot'.

Just to make it simple for beginners.

**Comment by jgorset** [comment]
Hi @db0sch! While we don't recommend building bots with Rails, we wrote a bit about it in the [README](https://github.com/hyperoslo/facebook-messenger#-on-rails). Do you think that's enough, and if not, how can we improve it? We're also happy to accept pull request. :smile:
