### ISSUE TITLE
Checking for attachments

### ISSUE THREAD

**Issue by raulriera** [hyperoslo/facebook-messenger#39]
Hi,

I have setup a simple bot and noticed that on your tests you are checking for attachments, but when I try to use it in code I get an error

```
NoMethodError: undefined method `attachments' for #<Facebook::Messenger::Incoming::Message:0x007fa4393f5dd8>
```

Also, it seems that this always returns false `message.respond_to? :attachments`. Any suggestions?

Thanks

**Comment by jgorset** [comment]
Hm! You might just be using an old version, then; attachments are new in 0.5.0. Which version are you on?

**Comment by raulriera** [comment]
You are correct, `facebook-messenger (0.4.2)` I installed the gem while reading up master, probably wasn't released by then.

Thanks! and sorry :)

**Comment by sindrenm** [comment]
No worries; glad I could help. Have a nice day. :smile:
