### ISSUE TITLE
beginner got an error i wonder if my folder files is correct or something is wrong?

### ISSUE THREAD

**Issue by ferryphang** [hyperoslo/facebook-messenger#42]
Hi thanks for making this gem. this is absolutely wonderful.
anyway i just try to play with the gem when i tried to run apps i got an error
`Facebook::Messenger::Error: An active access token must be used to query information about the current user.`
i wonder if my folder structure file is correct
https://github.com/ferryphang/SleepingForest
./bot.rb
./facebook/messenger.rb
./config.ru

**Comment by nashby** [comment]
@ferryphang hey, I think it's naming collision or something like that in your case. Can you try to rename folder "facebook/messenger" to something different? When you do `require facebook/messenger` you're actually requiring stuff from this gem, not your code.

**Comment by ferryphang** [comment]
@nashby ooh okay my bad i just tried to replace and require on the bot.rb for the Facebook configuration token. Thanks its working now. 👍

**Comment by nashby** [comment]
@ferryphang glad I could help! :)
