### ISSUE TITLE
How to integrate with a Sinatra app

### ISSUE THREAD

**Issue by catogonzalez** [hyperoslo/facebook-messenger#45]
Great gem! Thanks for sharing.

I am trying to implement this gem inside an existing Sinatra app. How should I change my `config.ru` to run my app and also the `Facebook::Messenger::Server`?

```ruby
# config.ru - of my existing app
require 'rubygems'
require 'sinatra'
require './my_app'
run Sinatra::Application
```

```ruby
# config.ru - for your gem
require 'facebook/messenger'
require_relative 'bot'
run Facebook::Messenger::Server
```

**Comment by frodsan** [comment]
```ruby
# config.ru
map "/" do
  run(Sinatra::Application)
end

map "/bot" do
  run(Facebook::Messenger::Server)
end
```

You can also set up the bot server in Sinatra with:

```ruby
map("/bot") { run(Facebook::Messenger::Server) }
```

**Comment by catogonzalez** [comment]
Fantastic!

Thanks a lot for your help Francesco; I am just starting with pure rack apps and this clears my path in many ways.
