### ISSUE TITLE
does not allow to pass sender_action to the .deliver  method

### ISSUE THREAD

**Issue by angelacode** [hyperoslo/facebook-messenger#54]
The Facebook API support the :sender_action to be passed to the .deliver method, but I get an error when I add that.

**Comment by timfong888** [comment]
Looks like it should just pass the value, but it gets an error: https://github.com/hyperoslo/facebook-messenger/blob/a72a09c86e92acc58752028d523a84f65a24a33b/lib/facebook/messenger/bot.rb#L20

**Comment by timfong888** [comment]
```
Facebook::Messenger::Bot::RecipientNotFound (#100) Cannot send both message and state at the same time
```

**Comment by timfong888** [comment]
If you only send one or the other then you're fine.

**Comment by angelacode** [comment]
okay confirmed.
