### ISSUE TITLE
Quick replies

### ISSUE THREAD

**Issue by edos4** [hyperoslo/facebook-messenger#63]
How do you send and receive quick replies?

**Comment by davidmann4** [comment]
hmm maybe this helps?
https://developers.facebook.com/docs/messenger-platform/send-api-reference/quick-replies

or

```ruby
Facebook::Messenger::Thread.set(
  setting_type: 'call_to_actions',
  thread_state: 'existing_thread',
  call_to_actions: [
    {
      type: 'postback',
      title: 'Help',
      payload: 'DEVELOPER_DEFINED_PAYLOAD_FOR_HELP'
    },
    {
      type: 'postback',
      title: 'Start a New Order',
      payload: 'DEVELOPER_DEFINED_PAYLOAD_FOR_START_ORDER'
    },
    {
      type: 'web_url',
      title: 'View Website',
      url: 'http://example.com/'
    }
  ]
)
```

let me know - I plan to add it to my starter project: https://github.com/davidmann4/fb-chatbot-framework-rails

**Comment by edos4** [comment]
Yep, done with creating quick replies. However, I cannot seem to catch them. They don't show up on `Bot.on :postback` and `Bot.on :message`.

**Comment by davidmann4** [comment]
You used type:postback ?

**Comment by jgorset** [comment]
That's not quite quick replies, though, @davidmann4, but it's close! This is [quick replies](https://developers.facebook.com/docs/messenger-platform/send-api-reference/quick-replies). You can send anything to `[Bot.deliver](https://github.com/hyperoslo/facebook-messenger/blob/master/lib/facebook/messenger/bot.rb#L21)` and it'll be forwarded to Facebook's API:

```
Bot.deliver  message: {
  text: 'Pick a color:',
  quick_replies: [
    { content_type: 'text', title: 'red', payload: 'DEVELOPER_DEFINED_PAYLOAD_FOR_PICKING_RED' },
    { content_type: 'text', title: 'red', payload: 'DEVELOPER_DEFINED_PAYLOAD_FOR_PICKING_RED' }
  ]
}

**Comment by jgorset** [comment]
Oh, I'm sorry @davidmann4, I got confused when I saw your code but I realize now that you already linked to quick replies.

**Comment by edos4** [comment]
Thanks guys. But how do you process the quick replies? Like if I got a `DEVELOPER_DEFINED_PAYLOAD_FOR_PICKING_RED`? Is it also a postback?

**Comment by jgorset** [comment]
Yep, that's a postback.

**Comment by jgorset** [comment]
Wait, no, [according to the documentation it's a new type of callback](https://developers.facebook.com/docs/messenger-platform/webhook-reference/message-received). We don't have that yet, so to make quick replies work we'll have to implement it (like we've implemented `Bot.on :message` and `Bot.on :postback`). We're happy to accept pull requests if you need it!

**Comment by edos4** [comment]
Thanks. :)

**Comment by jgorset** [comment]
I should keep this open, because we need this.

**Comment by jgorset** [comment]
Nevermind me; it's not a new callback, it's the same old "message received" callback. It even seems that we added support for quick replies in `Message` in https://github.com/hyperoslo/facebook-messenger/pull/53, but I fixed a bug in it and renamed it to `quick_reply` in a21f36e9883537dc1055c1fc16c4409c8504cc9e. It'll make it into master when https://github.com/hyperoslo/facebook-messenger/pull/67 is merged, and it's worth noting that it's backwards incompatible if you're using `quick_replies` today.

**Comment by jgorset** [comment]
So on a closing note, are you sure that you're not receiving the quick replies as messages in your message received callback, @edos4?

**Comment by edos4** [comment]
Will verify tomorrow when I arrive at the office. Thanks man!

**Comment by edos4** [comment]
Sorry for the late reply. Done by doing something like:
```
Bot.on :message do |message|
  if message.quick_replies.present?
      case message.quick_replies["payload"]
      when /string_here/i
        #code here
      end
  end
end
```
Thanks, @jgorset :)

**Comment by jgorset** [comment]
Great, thanks @edos4!

**Comment by jgorset** [comment]
Oh, and keep in mind that the interface is changing from `quick_replies` to `quick_reply` in the next version.

**Comment by chatbot66** [comment]
Where I need to define payloads for messenger chatbot??
function sendQuickReply(recipientId) {
  var messageData = {
    recipient: {
      id: recipientId
    },
    message: {
      text: "What's your favorite movie genre?",
      quick_replies: [
        {
          "content_type":"text",
          "title":"Action",
          "payload":"DEVELOPER_DEFINED_PAYLOAD_FOR_PICKING_ACTION"
        },
        {
          "content_type":"text",
          "title":"Comedy",
          "payload":"DEVELOPER_DEFINED_PAYLOAD_FOR_PICKING_COMEDY"
        },
        {
          "content_type":"text",
          "title":"Drama",
          "payload":"DEVELOPER_DEFINED_PAYLOAD_FOR_PICKING_DRAMA"
        }
      ]
    }
  };

  callSendAPI(messageData);
}
