### ISSUE TITLE
10+ elements

### ISSUE THREAD

**Issue by edos4** [hyperoslo/facebook-messenger#65]
What would be a good way to handle 10+ elements? 
Say for example,
```
elems = Element.all
elements = carts.map do |element|
  {
    title: element.name,
    subtitle: element.description,
    buttons: [
      {
        type: 'postback',
        title: 'View element',
        payload: {
          id: 'view_element',
          element_id: element.id
          sender: sender['id']
        }.to_json
      }
    ]
  }
end
```

**Comment by jgorset** [comment]
I'm not sure I understand, but that looks like an alright way to me! Can you elaborate what you're trying to do, and why you're trying to do it?

**Comment by edos4** [comment]
For example, I have 30 books. But Facebook only handles 10 elements. Come to think of it, this is probably a developer's responsibility. Will try it and post solution here. :) Closing this. Thanks.

**Comment by jgorset** [comment]
Alright, cool!
