### ISSUE TITLE
Rails 4.2.7 uninitialized constant Bot error

### ISSUE THREAD

**Issue by enderahmetyurt** [hyperoslo/facebook-messenger#66]
Hi, 
I tried to include facebook-messenger according to the documentation but I get error ``uninitialized constant Bot (NameError)``when I start the Rails server. How should I fix it?

**Comment by jgorset** [comment]
Hi @enderahmetyurt. Did you follow the [instructions for eager loading it](https://github.com/hyperoslo/facebook-messenger#-on-rails), too?

**Comment by enderahmetyurt** [comment]
Yes I did all of instructions. I fixed the problem with installing master branch.

**Comment by jgorset** [comment]
Alright, cool!
