### ISSUE TITLE
Can I get username?

### ISSUE THREAD

**Issue by enderahmetyurt** [hyperoslo/facebook-messenger#68]
Hi. I want to get message sender name instead of id? For example ```message.sender.name``` Is it possible?

**Comment by gauravtiwari** [comment]
@enderahmetyurt You could do as demonstrated in this thread - https://github.com/hyperoslo/facebook-messenger/issues/26  or use something like [koala](https://github.com/arsduo/koala) gem to interact with Facebook graph api and fetch the user details for any given `user_id`.

**Comment by enderahmetyurt** [comment]
Great. Thank you @gauravtiwari for solution. I am sorry I couldn't see #26 before :/
