### ISSUE TITLE
No hook registered

### ISSUE THREAD

**Issue by enderahmetyurt** [hyperoslo/facebook-messenger#72]
Hi,

I am trying to develop a bot in my existing Rails project. I created a bot on Facebook developer page and a webhook with ngrok. When I try to post from the Facebook to bot I see ```Ignoring message (no hook registered)``` error with ```Cannot render console from 173.252.90.106! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255"``` Do you have any idea about that?

Cheers.

**Comment by enderahmetyurt** [comment]
Sorry my mistake. I forgot to load the bot files. 😫

**Comment by sindrenm** [comment]
:grinning:
