### ISSUE TITLE
Name of user ?

### ISSUE THREAD

**Issue by rianfloo** [hyperoslo/facebook-messenger#74]
Is it possible to get the name of the user who is interacting with the bot?

**Comment by gauravtiwari** [comment]
Please check out this issue https://github.com/hyperoslo/facebook-messenger/issues/26

**Comment by rianfloo** [comment]
@gauravtiwari Thanks for the info! We used this solution for our bot : https://github.com/rianfloo/rails-gustave/ but it looks there is an update of Facebook Messenger that allow you the collect firstname and lastname : ```
<script>
    MessengerExtensions.getUserID(function success(uids) {
      var psid = uids.psid;
  
    }, function error(err) {      
  
    });    
</script> 
```
Is it possible to get all info thanks to your gem ?

**Comment by jgorset** [comment]
What is `MessengerExtensions`, @rianfloo? :-)

**Comment by enderahmetyurt** [comment]
the third question about getting name of user 😅

**Comment by rianfloo** [comment]
@jgorset : In the Facebook changelog: Added Webviews and Extensions to get user id for personalization, close the webview and call payments in the browser. 

URL => https://developers.facebook.com/docs/messenger-platform/send-api-reference/webview

**Comment by jgorset** [comment]
Okay, that's a JavaScript library provided by Facebook. It's the equivalent of using a library like [Koala](https://github.com/arsduo/koala) for Ruby. A bot's concern is to communicate with the user, so that's why we're not providing this feature in this library.
