### ISSUE TITLE
Messages with buttons error

### ISSUE THREAD

**Issue by enderahmetyurt** [hyperoslo/facebook-messenger#77]
Hi,

I am trying to get message from the user with message buttons. I read that block on Readme

```ruby
# Messages with buttons
# The human may require simple options to communicate:

Bot.deliver(
  recipient: {
    id: '45123'
  },
  message: {
    attachment: {
      type: 'template',
      payload: {
        template_type: 'button',
        text: 'Human, do you like me?',
        buttons: [
          { type: 'postback', title: 'Yes', payload: 'HARMLESS' },
          { type: 'postback', title: 'No', payload: 'EXTERMINATE' }
        ]
      }
    }
  }
)
```

and I think ```id``` means in here Facebook Page Id. Am I right? I checked the Facebook Messenger Documentation. However, I set the my page id, I see some errors on my Rails server logs. My sending message code is 

```ruby
Bot.on :postback do |postback|
  if postback.payload == 'CLICK_GET_STARTED'
    Bot.deliver(
      recipient: {
        id: postback.recipient
      },
      message: {
        attachment: {
          type: "template",
          payload: {
            template_type: "button",
            text: "Are you okey?",
            buttons: [
              { type: 'postback', title: "Yes", payload: "YES" },
              { type: 'postback', title: "No", payload: "NO" }
            ]
          }
        }
      }
    )
  end
end
```

And the error is ```Facebook::Messenger::Bot::RecipientNotFound - (#100) Parameter recipient[id]: Invalid id: {"id":"my_page_id"}:```

After that error I checked my page with that URL ```https://www.facebook.com/profile.php?id=my_page_id``` I saw my page.

Where is the wrong in that code? Any idea?

Cheers.

**Comment by jgorset** [comment]
`recipient.id` is the user you want to send a message to, and it's unique for each page. When you get a message from a user, you'll find it in [`Incoming::Message#sender`](https://github.com/hyperoslo/facebook-messenger/blob/master/lib/facebook/messenger/incoming/message.rb#L16).

**Comment by jgorset** [comment]
See the bit about [Sending and receiving messages in the README](https://github.com/hyperoslo/facebook-messenger#sending-and-receiving-messages) for an example.

**Comment by enderahmetyurt** [comment]
@jgorset but it's a postback not message. Can I show Yes/No button in message block?
