### ISSUE TITLE
Bot is not responding after clicking the like button

### ISSUE THREAD

**Issue by ozbaysa** [hyperoslo/facebook-messenger#81]
My bot stops responding after some body sends it like. For example it works great with text but when you click the like button on the messenger it stops and after the clicking the like button, bot still not responds any text. So let me be more clear;      1- Human        2- Bot
1- SOME TEXT
2- RESPOND(done)
1-SENDING LIKE ON MESSENGER
2-NO RESPOND
1-SOME TEXT
2-NO RESPOND
.....
2- NO RESPOND

**Comment by jgorset** [comment]
I'm not able to reproduce this, @ozbaysa. What do your server logs look like for receiving the like? These are mine:

```
66.220.152.187 - - [22/Oct/2016:15:08:12 +0200] "POST / HTTP/1.1" 200 - 0.0008
Received '#<Facebook::Messenger::Incoming::Message:0x007fc38ea36ac0 @messaging={"sender"=>{"id"=>"1083979811657628"}, "recipient"=>{"id"=>"168672563538062"}, "timestamp"=>1477141693554, "message"=>{"mid"=>"mid.1477141693554:7127130957", "seq"=>88, "sticker_id"=>369239263222822, "attachments"=>[{"type"=>"image", "payload"=>{"url"=>"https://scontent.xx.fbcdn.net/t39.1997-6/851557_369239266556155_759568595_n.png?_nc_ad=z-m", "sticker_id"=>369239263222822}}]}}>' from {"id"=>"1083979811657628"}
```

<img width="667" alt="screen shot 2016-10-22 at 15 08 52" src="https://cloud.githubusercontent.com/assets/195266/19619515/a8eaaf28-9869-11e6-97da-bf6b1540c60e.png">

**Comment by enderahmetyurt** [comment]
I guess @ozbaysa code does not include :postpack block. Like button should be a postback so the :message block cannot handle it.

**Comment by jgorset** [comment]
I think it's a message, actually, @enderahmetyurt, judging from the payload. It's a "sticker".

**Comment by jgorset** [comment]
```
"message" => {
  "mid" => "mid.1477141693554:7127130957",
  "seq" => 88,
  "sticker_id" => 369239263222822,
  "attachments" => [
    {
      "type" => "image",
      "payload" => {
        "url" = > "https://scontent.xx.fbcdn.net/t39.1997-6/851557_369239266556155_759568595_n.png?_nc_ad=z-m",
        "sticker_id" = >369239263222822
       }
     }
  ]
}
```

**Comment by enderahmetyurt** [comment]
Yes, you're right @jgorset i missed that point 😳

**Comment by jgorset** [comment]
Either way, it should definitely not stop consecutive messages from arriving (and it seems to me that it does not)! 😄
