### ISSUE TITLE
Text message identifier

### ISSUE THREAD

**Issue by enderahmetyurt** [hyperoslo/facebook-messenger#82]
Hi,

It's should be a silly question but I cannot handle the problem. Should I separate the text messages? How can I teach the bot which message it must answer.

For example, **B:** Bot, **U:** User
**B:** Where are you from?
**U:** I am from Turkey.
**B:** Which city did you born in Turkey?
**U:** I was born in Istanbul.
**B:** When did you born in Istanbul?
**U:** in 1986.

In that example the bot should understand the sequence of the messages. It should answer the questions in order.

It's just an example. I can use regex in here but my scenario is more complex than the example. I tried to use ```metadata``` but I see that I cannot get from user message. I made a class which have some attributes ```message_id, message_text``` and ```previous_message_id```. I initialized the class when user writes an answers but in that time bot answered the all questions :/ It have should quited the ```:message``` block.

My point is that bot should know the next right question after user text message.

Cheers.

**Comment by gauravtiwari** [comment]
Hey @enderahmetyurt 

The sequence solution could be tricky unless you are making sure a user asks the question in same order no matter what. Regex can also produce edge case considering all users won't type consistently. 

I guess a probable solution would be to use contexts, meaning giving bot some sort of background about each question and then use that context to call dynamic methods to fetch and show specific data. For ex: If someone asks, where are you from? Then, you can train the bot that if a word `where`  is involved then a user is more likely asking for some sort of location. And then I guess somehow you can group and map these contexts to reduce duplication. 

You can take a look at this website and see how they use contexts and entities. https://wit.ai/docs/quickstart

**Comment by enderahmetyurt** [comment]
Thank you for quick reply @gauravtiwari. I will try wit.ai I hope it will solve my problem 🙏
