### ISSUE TITLE
Ignoring Message (No hook register) 

### ISSUE THREAD

**Issue by prdpspkt** [hyperoslo/facebook-messenger#85]
This is not an issue with gem but issue with myself. I didn't know how this errors has been received. I have use just given code below and setup bot. Facebook posts to my server but i get message in console as "Ignoring message, no hook registered". Can you please tell me the reason and close issue. Thank in Advance

```
#app/bot.rb
  require 'facebook/messenger'
  include Facebook::Messenger
  Bot.on :message do |message|
   Bot.deliver(
     recipient: message.sender,
     message: {
      text: 'Hello, human!'
    }
  )
end
Bot.on :optin do |optin|
Bot.deliver(
    recipient: optin.sender,
    message: {
      text: 'Ah, human!'
    }
  )
end
Bot.on :delivery do |delivery| 
 puts "Human was online at #{delivery.at}"
end
Facebook::Messenger::Thread.set(
  setting_type: 'greeting',
  greeting: {
    text: 'Welcome to your new bot overlord!'
  }
)
```

**Comment by enderahmetyurt** [comment]
Please paste your example codes in a code block check it out [https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code](https://help.github.com/articles/basic-writing-and-formatting-syntax/#quoting-code)

**Comment by enderahmetyurt** [comment]
You need to get rid of these message. You should set ```read```block.

**Comment by am4501** [comment]
Hello,
I created a bot on Facebook developer page and a webhook with ngrok. When I try to post from the Facebook to bot I see Ignoring message (no hook registered) error with Cannot render console from 173.252.90.106! Allowed networks: 127.0.0.1, ::1, 127.0.0.0/127.255.255.255" 
Please help to resolve this!

`
require 'facebook/messenger'

include Facebook::Messenger

Bot.on :message do |message|
  message.id          # => 'mid.1457764197618:41d102a3e1ae206a38'
  message.sender      # => { 'id' => '1008372609250235' }
  message.seq         # => 73
  message.sent_at     # => 2016-04-22 21:30:36 +0200
  message.text        # => 'Hello, bot!'
  message.attachments # => [ { 'type' => 'image', 'payload' => { 'url' => 'https://www.example.com/1.jpg' } } ]

  message.reply(text: 'Hello, human!')
end
`

**Comment by enderahmetyurt** [comment]
You need to write receiving messages blocks. Please check https://github.com/hyperoslo/facebook-messenger/blob/master/examples/bot.rb

**Comment by am4501** [comment]
I've tried to use bot.rb from the provided example but still getting "Ignoring message (no hook registered)" Here is the link to my project. Please help!

[https://github.com/am4501/bot](url)

**Comment by kevinchandler** [comment]
@am4501 and anyone else coming across this it's likely you don't have `ENV['ACCESS_TOKEN']` set
