### ISSUE TITLE
iPad read block problem

### ISSUE THREAD

**Issue by enderahmetyurt** [hyperoslo/facebook-messenger#88]
Hi,
I am trying to send text message to bot via iPad mini. After bot sends a text message, user reads the message and the program should visit "read" block. It works on web and mobile messenger but not working on iPad messenger. Have you faced same problem?

Cheers.

**Comment by enderahmetyurt** [comment]
Not working on mobile aswell :(

**Comment by jgorset** [comment]
That's really weird, but it's got to be a problem on Facebook's end – we treat all those the same.

**Comment by jgorset** [comment]
I would file this issue on Facebook's bug tracker, @enderahmetyurt.
