### ISSUE TITLE
NoMethodError

### ISSUE THREAD

**Issue by AlecRubin** [hyperoslo/facebook-messenger#9]
I was able to get through about 90% of the installation process. Facebook accepted the webhook, but when I go to message my bot, I don't get a response, so I looked at the logs on my server and I'm getting this.

NoMethodError (undefined method `fetch' for nil:NilClass):

Any clue what's wrong?

**Comment by frodsan** [comment]
Can you create a script that reproduces this issue?

**Comment by frodsan** [comment]
I think it's because of this line:

https://github.com/hyperoslo/facebook-messenger/blob/master/lib/facebook/messenger/bot.rb#L63

If there are no hooks registered, @hooks will be nil.

**Comment by frodsan** [comment]
Here is an example:

```
require "bundler/setup"
require_relative "lib/facebook/messenger"

Facebook::Messenger::Bot.trigger(:message, 'o')
facebook-messenger/lib/facebook/messenger/bot.rb:63:in `trigger': undefined method `fetch' for nil:NilClass (NoMethodError)
```

**Comment by frodsan** [comment]
After #10, the result is:

```ruby
require "bundler/setup"
require_relative "lib/facebook/messenger"

Facebook::Messenger::Bot.trigger(:message, 'o')
# => Ignoring message (no hook registered)
```

**Comment by AlecRubin** [comment]
How do you register a hook?

**Comment by jgorset** [comment]
That seems a likely culprit, @frodsan. If you give us the full stack trace we'll know for sure, though, @AlecRubin.

**Comment by jgorset** [comment]
When @frodsan refers to hook, he means `Bot.on :something`. We call those somethings hooks internally.

**Comment by frodsan** [comment]
Can you try your script with 0.4.0? https://rubygems.org/gems/facebook-messenger/versions/0.4.0

**Comment by jgorset** [comment]
I'm gonna close this pending a reply from @AlecRubin.
