### ISSUE TITLE
Bot message.reply raise NoMethodError

### ISSUE THREAD

**Issue by fengarix** [hyperoslo/facebook-messenger#93]
This is my code when i try to reply a message
```
include Facebook::Messenger

Bot.on :message do |msg|
  msg.reply({text: 'lala'})
end
```
But when i message my bot it raise error 
```NoMethodError (undefined method `reply' for #<Facebook::Messenger::Incoming::Message:0x007fb5f4b9aa30>):```

**Comment by jgorset** [comment]
`reply` had not made it into a version yet, but I [just released v0.11.0](https://github.com/hyperoslo/facebook-messenger/commit/fe479e3f8e5182388208417da5de32269f97473d). Please update use that feature.
