### ISSUE TITLE
Bot.deliver error handling

### ISSUE THREAD

**Issue by pjpires** [hyperoslo/facebook-messenger#96]
As the API is growing at Facebook, it appears some new error codes are being returned.

We've been working with the API for the last weeks, and I'm almost sure that when someone deleted a conversation with a bot, Facebook would return 100 error in response to the `Bot.deliver` action, a `Facebook::Messenger::Bot::RecipientNotFound`.

Now, apparently it is returning a new error code, 200, per the API: 
"This person isn't receiving messages from you right now."

I'm relying on these errors to keep track of the real bot users (I destroy those who don't receive messages), so it would be cool either to upgrade the gem with the recently added error responses (https://developers.facebook.com/docs/messenger-platform/send-api-reference#response) or wrap the errors in the exceptions in a way that the code was still available for us to check, e.g., see: https://github.com/ryanb/cancan/blob/master/lib/cancan/exceptions.rb#L35.

Any thoughts on this?
Thanks in advance.

**Comment by jgorset** [comment]
I think that'd be _awesome_, @pjpires! I'd be very happy to merge a pull request with new and improved error handling (and I like the approach where each error has its own exception that you can rescue from).

**Comment by pjpires** [comment]
@jgorset took me a while to have time for it, but what do you think about this?
https://github.com/hyperoslo/facebook-messenger/pull/99

**Comment by jgorset** [comment]
Love it, @pjpires – merged. :wink:
