### ISSUE TITLE
Return 200 OK HTTP fast

### ISSUE THREAD

**Issue by massens** [hyperoslo/facebook-messenger#97]
I have a rails application. The webhook callback sometimes is a bit slow to return a 200 OK HTTP response, as it has to interact with other APIs before. This makes facebook send the app duplicated requests. 

How can I send back as fast as possible 200 OK HTTP message once i've received a message in `
Bot.on :message do |message|
`?

Thanks

**Comment by sorich87** [comment]
Just run your API requests and send the reply in a queue using Active Job.
